spring:
  application:
    name: bodhganga
  data:
    mongodb:
      uri: mongodb+srv://<username>:<password>@random.30wadid.mongodb.net/bodhganga?retryWrites=true&w=majority&appName=test-bodhganga
      auto-index-creation: true

server:
  port: ${PORT:9090}

jwt:
  secret: jwtsecret
  expiration: 86400000
