spring.application.name=bodhganga

# Server Configuration
server.port=9090

# MongoDB Configuration (Local - Commented Out)
# spring.mongodb.port=27017
# spring.mongodb.uri=mongodb://localhost:27017/bodhganga

# MongoDB Configuration (Atlas - Uncomment and update below)
# PASTE YOUR CONNECTION STRING HERE
spring.data.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.mongodb.net/bodhganga?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=jwtseret
jwt.expiration=86400000
# 24 hours in milliseconds
